<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<RootNamespace>Keyfactor.Extensions.CAPlugin.HydrantId</RootNamespace>
		<AssemblyName>HydrantIdCAPlugin</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Keyfactor.AnyGateway.IAnyCAPlugin" Version="3.3.0" />
        <PackageReference Include="Keyfactor.Logging" Version="1.1.1" />
        <PackageReference Include="Keyfactor.PKI" Version="5.5.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.25" />
	</ItemGroup>
	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
